export class Aqlbypass {
    public Status: string
    public Closed_y: string
    public Closed_Date: string
    public ReceiptType: string
    public ReceiptGroup: string
    public Program_Ind: string
    public Susr1: string
    public Susr2: string
    public PlaceofLoading: string
    public Susr3: string
    public Susr5: string
    public ProgramName: string
    public AddDate: string
    public AddWho: string
    public EditDate: string
    public EditWho: string
    public ExternKey: string
    public Vendorid: string
    public Susr4: string
    public Receipttrans: string
    public PlaceofDelivery: string
    public ShipmentReferenceNumber: string
    public Clientid: string
    public SiteId: string
    public Receiptkey: string
    public ExternReceiptkey: string
    public ReceiptDate: string;
    public ShipDate: string;
    public Client_System_Cd: string
    public CustomerName: string
    public Route: string
    public Address1: string
    public Address3: string
    public Address4: string
    public City: string
    public State: string
    public Zip: string
    public Country: string
    public Phone: string
    public CarrierReference: string
    public Address2: string
    public ReceiptDetail: any;
}